logging:
  config: 'classpath:buggy-logback.xml'
  file:
    path: logs
buggy:
  commandsScannerBasePackages:
    - "**.buggy"
  goalsScannerBasePackages:
    - "**.buggy"
  suitesScannerBasePackages:
    - "**.buggy"
  listenersScannerBasePackages:
    - "**.buggy"