logging:
  config: 'classpath:buggy-logback.xml'
spring:
  main:
    allow-bean-definition-overriding: true
buggy:
  configuration:
    testng:
      scanner:
        suite:
          basePackage: "**.buggy"
          useDefaultFilters: false
        listener:
          basePackage: "**.buggy"
          useDefaultFilters: false