stages:
  - build

variables:
  SONAR_ARGS: "-Dsonar.gitlab.commit_sha=${CI_COMMIT_SHA} -Dsonar.gitlab.ref_name=${CI_COMMIT_REF_NAME}"

Buggy:
  stage: build
  tags:
    - touchbit-shell
  script:
    - mvn clean install
    - >
      if [ "$CI_BUILD_REF_NAME" == "master" ]; then
        mvn sonar:sonar -Dsonar.login=$SONAR_LOGIN $SONAR_ARGS
      else
        mvn sonar:sonar -Dsonar.login=$SONAR_LOGIN $SONAR_ARGS -Dsonar.analysis.mode=preview
      fi
