stages:
  - build
  - test
  - analyse
  - deploy

variables:
  SONAR_ARGS: "-Dsonar.gitlab.commit_sha=${CI_COMMIT_SHA} -Dsonar.gitlab.ref_name=${CI_COMMIT_REF_NAME}"

Build Buggy:
  stage: build
  tags:
    - touchbit-shell
  script:
    - mvn clean install -Dmaven.test.skip=true

Buggy-core test:
  stage: test
  tags:
    - touchbit-shell
  script:
    - cd buggy-core
    - mvn test
  artifacts:
    name: buggy
    paths:
      - "*/target/reports"
      - "*/target/classes"

Buggy-feign test:
  stage: test
  tags:
    - touchbit-shell
  script:
    - cd buggy-feign
    - mvn test
  artifacts:
    name: buggy
    paths:
      - "*/target/reports"
      - "*/target/classes"

Buggy-okhttp test:
  stage: test
  tags:
    - touchbit-shell
  script:
    - cd buggy-okhttp
    - mvn test
  artifacts:
    name: buggy
    paths:
      - "*/target/reports"
      - "*/target/classes"

Sonar:
  stage: analyse
  dependencies:
    - Buggy-core test
    - Buggy-feign test
    - Buggy-okhttp test
  tags:
    - touchbit-shell
  script:
    - >
      if [ "$CI_BUILD_REF_NAME" == "master" ]; then
        mvn sonar:sonar -Dsonar.login=$SONAR_LOGIN $SONAR_ARGS
      else
        mvn sonar:sonar -Dsonar.login=$SONAR_LOGIN $SONAR_ARGS -Dsonar.analysis.mode=preview
      fi

Deploy Buggy:
  stage: deploy
  dependencies:
    - Sonar
#  only:
#    - master
  script:
    - mvn deploy -Dmaven.test.skip=true

