stages:
  - build
  - deploy

variables:
  SONAR_ARGS: "-Dsonar.gitlab.commit_sha=${CI_COMMIT_SHA} -Dsonar.gitlab.ref_name=${CI_COMMIT_REF_NAME}"

Project:
  stage: build
  tags:
    - touchbit-shell
  script:
    - mvn clean verify
    - >
      if [ "$CI_BUILD_REF_NAME" == "master" ]; then
        mvn sonar:sonar -Dsonar.login=$SONAR_LOGIN $SONAR_ARGS
      else
        mvn sonar:sonar -Dsonar.login=$SONAR_LOGIN $SONAR_ARGS -Dsonar.analysis.mode=preview
      fi

Buggy modules:
  stage: deploy
#  only:
#    - master
  when: on_success
  script:
    - mvn deploy -Dmaven.test.skip=true