stages:
  - build
  - test
  - verify
  - deploy

variables:
  SONAR_ARGS: "-Dsonar.gitlab.commit_sha=${CI_COMMIT_SHA} -Dsonar.gitlab.ref_name=${CI_COMMIT_REF_NAME}"

Build Buggy:
  stage: build
  tags:
    - touchbit-shell
  script:
    # do not use -Dmaven.test.skip=true
    - mvn clean install -DskipTests
    - mv buggy-min-example/target/Buggy.jar MinBuggy.jar
  artifacts:
    expire_in: 1 day
    paths:
      - "*Buggy.jar"

Buggy-core test:
  stage: test
  tags:
    - touchbit-shell
  script:
    - cd buggy-core
    - mvn test
  artifacts:
    expire_in: 1 day
    paths:
      - "*/target/reports"

Buggy-feign test:
  stage: test
  tags:
    - touchbit-shell
  script:
    - cd buggy-feign
    - mvn test
  artifacts:
    expire_in: 1 day
    paths:
      - "*/target/reports"

Buggy-okhttp test:
  stage: test
  tags:
    - touchbit-shell
  script:
    - cd buggy-okhttp
    - mvn test
  artifacts:
    expire_in: 1 day
    paths:
      - "*/target/reports"

Sonar review:
  stage: verify
  dependencies:
    - Buggy-core test
    - Buggy-feign test
    - Buggy-okhttp test
  tags:
    - touchbit-shell
  script:
    - >
      if [ "$CI_BUILD_REF_NAME" == "master" ]; then
        mvn compile sonar:sonar -Dsonar.login=$SONAR_LOGIN $SONAR_ARGS
      else
        mvn compile sonar:sonar -Dsonar.login=$SONAR_LOGIN $SONAR_ARGS -Dsonar.analysis.mode=preview
      fi

Min Buggy run:
  stage: verify
  variables:
    GIT_STRATEGY: none
  dependencies:
    - Build Buggy
  tags:
    - touchbit-shell
  script:
    - java -jar MinBuggy.jar --check
    - java -jar MinBuggy.jar
    - java -jar MinBuggy.jar --force --status 0 --artifacts-url "$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/"
  artifacts:
    expire_in: 1 day
    paths:
      - "logs"

Deploy Snapshot:
  stage: deploy
  tags:
    - touchbit-shell
  except:
    - tags
  when: manual
  script:
    - BUGGY_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
    - SNAPSHOT_BUGGY_VERSION=${BUGGY_VERSION}-SNAPSHOT
    - mvn versions:set -DnewVersion=${SNAPSHOT_BUGGY_VERSION}
    - mvn deploy -Dmaven.test.skip=true
    - "curl -X POST \"https://api.telegram.org/bot$BABBLER_TOKEN/sendMessage?chat_id=$TELEGRAM_BUGGY_CI_CD_CHAT_ID&disable_notification=true&parse_mode=Markdown&text=*Buggy*%0ANew version deployed: %5B${SNAPSHOT_BUGGY_VERSION}%5D%28https://touchbit.org/repository/org/touchbit/buggy/buggy/${SNAPSHOT_BUGGY_VERSION}/%29\""

Deploy Buggy:
  stage: deploy
  tags:
    - touchbit-shell
  before_script:
    - mvn versions:set -DnewVersion=$CI_COMMIT_TAG
    - mvn dependency:purge-local-repository@local-buggy
    - mvn dependency:get@current-version && CHECK_RESULT=$(echo $?) || CHECK_RESULT=$(echo $?)
    - >
      if [ "${CHECK_RESULT}" != 1 ]; then
          if [[ "${CI_COMMIT_MESSAGE,,}" = *"force deploy"* ]]; then
              echo "Force deploy tag version: ${CI_COMMIT_TAG}";
          else
              BUGGY_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
              echo "[ERROR] The current version of Buggy ($BUGGY_VERSION) already exists in the TouchBIT repository"
              echo "To set the new version, use the command: 'mvn versions:set -DnewVersion=<new version>'"
              echo "Versioning rules: https://semver.org/spec/v2.0.0-rc.2.html"
              false
          fi
      fi
  only:
    - tags
  script:
    - mvn versions:set -DnewVersion=$CI_COMMIT_TAG
    - mvn deploy
    - BUGGY_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
    - "curl -X POST \"https://api.telegram.org/bot$BABBLER_TOKEN/sendMessage?chat_id=$TELEGRAM_BUGGY_CI_CD_CHAT_ID&disable_notification=false&parse_mode=Markdown&text=*Buggy*%0ANew version deployed: %5B${BUGGY_VERSION}%5D%28https://touchbit.org/repository/org/touchbit/buggy/buggy/${BUGGY_VERSION}/%29\""