include: https://gitlab.com/TouchBIT/gitlab-ci/raw/master/common.yml

Buggy:
  extends: .build_java_project
  variables:
    SKIP_TEST: "true"
  after_script:
    - mv buggy-min-example/target/Buggy.jar MinBuggy.jar
  artifacts:
    when: always
    expire_in: 30 day
    paths:
      - "*/target/reports"
      - "*Buggy.jar"

Sphinx doc:
  extends: .build_sphinx_doc
  variables:
    DOCKERFILE: docs/Dockerfile

JUnit:
  extends: .junit_test_run

Sonar review:
  extends: .sonar_review
  dependencies:
    - JUnit

Min Buggy run:
  stage: verify
  variables:
    GIT_STRATEGY: none
  dependencies:
    - Buggy
  tags:
    - touchbit-shell
  script:
    - java -jar MinBuggy.jar --check
    - java -jar MinBuggy.jar --force --status 0 --artifacts-url "$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/"
  artifacts:
    expire_in: 1 day
    paths:
      - "*/logs"

Release:
  extends: .trigger_release_deploy

Snapshot:
  extends: .trigger_snapshot_deploy